name: Compiler

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 15, 16]

    steps:
      - uses: actions/checkout@v3
      - name: NPM
        run: |
          npm install
      - name: Compile
        run: |
          npm run compile
